ARCH_LIBSOURCES:=uCOS-III/Ports/ARM-Cortex-A/Generic/GNU/os_cpu_a_vfp-d32.S \
                 uCOS-III/Ports/ARM-Cortex-A/Generic/GNU/os_cpu_c.c \
                 bsp/ps7/ucos_osiii_bsp.c


ARCH_INCLUDEFILES:=uCOS-III/Ports/ARM-Cortex-A/Generic/GNU/os_cpu.h \
                   bsp/ps7/ucos_osiii_bsp.h
              