ARCH_LIBSOURCES:= ps7/ucos_impl.c \
                  ps7/ucos_int_impl.c \
                  ps7/asm_vectors.S \
                  ps7/mmu_blank.S


ARCH_INCLUDEFILES:=ps7/ucos_int_impl.h \
                   ps7/ucos_impl.h
