ARCH_LIBSOURCES:=uCOS-III/Ports/MicroBlaze/GNU/os_cpu_a.S \
                 uCOS-III/Ports/MicroBlaze/GNU/os_cpu_c.c \
                 bsp/mb/ucos_osiii_bsp.c


ARCH_INCLUDEFILES:=${UCOS_SRC_BASE}/uCOS-III/Ports/MicroBlaze/GNU/os_cpu.h \
                   bsp/mb/ucos_osiii_bsp.h
