ARCH_LIBSOURCES:=uCOS-II/Ports/ARM-Cortex-A50/Generic/GNU/os_cpu_a.S \
                 uCOS-II/Ports/ARM-Cortex-A50/Generic/GNU/os_cpu_c.c \
                 bsp/psua53/ucos_osii_bsp.c \
                 bsp/psua53/ucos_osii_bsp_a.S


ARCH_INCLUDEFILES:=uCOS-II/Ports/ARM-Cortex-A50/Generic/GNU/os_cpu.h \
                   bsp/psua53/ucos_osii_bsp.h
              