ARCH_LIBSOURCES:=uCOS-II/Ports/MicroBlaze/GNU/os_cpu_a.s \
                 uCOS-II/Ports/MicroBlaze/GNU/os_cpu_c.c \
                 bsp/mb/ucos_osii_bsp.c
            
            
ARCH_INCLUDEFILES:=uCOS-II/Ports/MicroBlaze/GNU/os_cpu.h \
                   bsp/mb/ucos_osii_bsp.h
