ARCH_LIBSOURCES:=uCOS-II/Ports/ARM-Cortex-A/Generic/GNU/os_cpu_a_vfp-none.S \
                 uCOS-II/Ports/ARM-Cortex-A/Generic/GNU/os_cpu_c.c \
                 bsp/psur5/ucos_osii_bsp.c


ARCH_INCLUDEFILES:=uCOS-II/Ports/ARM-Cortex-A/Generic/GNU/os_cpu.h \
                   bsp/psur5/ucos_osii_bsp.h
              