
#include  <lib_def.h>
#include  <cpu.h>

typedef struct ttcps *TTCPS_PTR;

typedef struct {
    CPU_INT32U DeviceId;
    CPU_INT32U BaseAddress;
    CPU_INT32U ClockFreq;
} UCOS_TTCPS_Config;

typedef struct {
    CPU_INT32U DeviceId;
    TTCPS_PTR  Timer;
} UCOS_TTCPS;

typedef UCOS_TTCPS *UCOS_TTCPS_HANDLE;

#define UCOS_TTCPS_IXR_INTERVAL DEF_BIT_00
#define UCOS_TTCPS_IXR_MATCH0   DEF_BIT_01
#define UCOS_TTCPS_IXR_MATCH1   DEF_BIT_02
#define UCOS_TTCPS_IXR_MATCH2   DEF_BIT_03
#define UCOS_TTCPS_IXR_CNT_OVR  DEF_BIT_04
#define UCOS_TTCPS_IXR_EV       DEF_BIT_05
#define UCOS_TTCPS_IXR_MASK     0x3F

UCOS_TTCPS_HANDLE UCOS_TTCPSInit (CPU_INT32U DeviceId);
CPU_BOOLEAN UCOS_TTCPSStart (UCOS_TTCPS_HANDLE Handle);
CPU_BOOLEAN UCOS_TTCPSStop (UCOS_TTCPS_HANDLE Handle);
CPU_BOOLEAN UCOS_TTCPSIntSet (UCOS_TTCPS_HANDLE Handle, CPU_INT32U Int);
CPU_BOOLEAN UCOS_TTCPSIntClr (UCOS_TTCPS_HANDLE Handle, CPU_INT32U Int);
CPU_INT32U UCOS_TTCPSIntStatGet (UCOS_TTCPS_HANDLE Handle);
