ARCH_LIBSOURCES:=uC-CPU/ARM-Cortex-A/GNU/cpu_a.S \
                 uC-CPU/Cache/ARM/armv7_generic_l1_l2c310_l2/cpu_cache_armv7_generic_l1_l2c310_l2.c \
                 uC-CPU/Cache/ARM/armv7_generic_l1_l2c310_l2/GNU/cpu_cache_armv7_generic_l1_l2c310_l2_a.S \
                 ps7/cpu_bsp.c


ARCH_INCLUDEFILES:=${UCOS_SRC_BASE}/uC-CPU/ARM-Cortex-A/GNU/cpu.h
