ARCH_LIBSOURCES:= psur5/ucos_impl.c \
                  psur5/ucos_int_impl.c \
                  psur5/asm_vectors.S \
                  psur5/mmu_blank.S \
                  ipi/ucos_int_ipi.c


ARCH_INCLUDEFILES:=psur5/ucos_int_impl.h \
                   psur5/ucos_impl.h \
                   ipi/ucos_int_ipi.h
                   
