ARCH_LIBSOURCES:=uCOS-III/Ports/ARM-Cortex-A50/Generic/GNU/os_cpu_a.S \
                 uCOS-III/Ports/ARM-Cortex-A50/Generic/GNU/os_cpu_c.c \
                 bsp/psua53/ucos_osiii_bsp.c


ARCH_INCLUDEFILES:=uCOS-III/Ports/ARM-Cortex-A50/Generic/GNU/os_cpu.h \
                   bsp/psua53/ucos_osiii_bsp.h
              