ARCH_LIBSOURCES:=uCOS-III/Ports/ARM-Cortex-A/Generic/GNU/os_cpu_a_vfp-none.S \
                 uCOS-III/Ports/ARM-Cortex-A/Generic/GNU/os_cpu_c.c \
                 bsp/psur5/ucos_osiii_bsp.c


ARCH_INCLUDEFILES:=uCOS-III/Ports/ARM-Cortex-A/Generic/GNU/os_cpu.h \
                   bsp/psur5/ucos_osiii_bsp.h
              