ARCH_LIBSOURCES:= psua53/ucos_impl.c \
                  psua53/ucos_int_impl.c \
                  psua53/asm_vector.S \
                  psua53/translation_table.S \
                  ipi/ucos_int_ipi.c


ARCH_INCLUDEFILES:=psua53/ucos_int_impl.h \
                   psua53/ucos_impl.h \
                   ipi/ucos_int_ipi.h
